import AuthApi from './authRepository';
import Zip from './zipRepository';
import Profile from './profileRepository';
import Tutor from './tutorRepository';
import Address from './addressRepository';
import Certification from './certificationsRepository';
import Department from './departmentsRepository';
import AcademicProgram from './academicProgramRepository';
import File from './filesRepository';
import Colleges from './collegeRepository';
import SubjectToCourse from './subjectToCourseApi';

export const Auth = AuthApi;
export const ZipApi = Zip;
export const TutorApi = Tutor;
export const AddressApi = Address;
export const CertificationApi = Certification;
export const DepartmentApi = Department;
export const AcademicProgramApi = AcademicProgram;
export const ProfileApi = Profile;
export const FileApi = File;
export const SubjectToCourseApi = SubjectToCourse;
export const CollegeApi = Colleges;